CREATE TABLE IF NOT EXISTS user(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username  UNIQUE FULLtext NOT NULL CHECK (name <> ''),
    password varchar(50) NOT NULL,
    name text varchar(50) NOT NULL,
    email varchar(50) NOT NULL,
    enable BOOLEAN(1),
);

CREATE TABLE IF NOT EXISTS characters(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image  varchar(250) NOT NULL,
    name text varchar(50) NOT NULL,
    age INTEGER NULL,
    history varchar(1000) NOT NULL,
    weight INTEGER NULL,
);

CREATE TABLE IF NOT EXISTS movies(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image varchar(250) NOT NULL,
    title text varchar(250) NOT NULL,
    creationdate DATE NOT NULL,
    calification INTEGER NULL,
);

CREATE TABLE IF NOT EXISTS gendertype(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description  text varchar(50) NOT NULL,
);

CREATE TABLE IF NOT EXISTS contenttype(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description  text varchar(50) NOT NULL,
);

INSERT INTO user(id, username, password, name, email)
    VALUES ('1', 'LOLO45', '1234', 'LOLO', 'lolo45@gmail.com');

INSERT INTO user(id, username, password, name, email)
    VALUES ('2', 'PEPE', '12345', 'PEPE', 'pepe45@gmail.com');

INSERT INTO characters(id, image, name, age, history, weight)
    VALUES ('10', '', 'PLUTO', '7', 'ES UN PERRO', '25');


INSERT INTO movies(id, image, title, creationdate, calification)
    VALUES ('20', '', 'PLUTO Y SUS AMIGOS', '02/10/1990', '8');

INSERT INTO gendertype(id, descripcion)
    VALUES ('30', 'INFANTIL');

INSERT INTO contenttype(id, description)
    VALUES ('40', 'APTO PARA TODO PUBLICO');




    